import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-black text-white relative">
        {/* Global Starry Background */}
        <div className="fixed inset-0 z-[-2] bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-blue-950/20 via-black to-black">
          <div className="absolute top-[10%] left-[5%] w-1 h-1 bg-white rounded-full shadow-[0_0_10px_2px_#fff] animate-pulse"></div>
          <div className="absolute top-[30%] left-[85%] w-1.5 h-1.5 bg-yellow-100 rounded-full shadow-[0_0_15px_3px_#fef08a] opacity-60"></div>
          <div className="absolute top-[60%] left-[15%] w-1 h-1 bg-blue-100 rounded-full shadow-[0_0_12px_2px_#bfdbfe] opacity-50 animate-pulse"></div>
          <div className="absolute top-[85%] left-[75%] w-1 h-1 bg-white rounded-full shadow-[0_0_8px_1px_#fff]"></div>
          <div className="absolute top-[45%] left-[45%] w-1 h-1 bg-white rounded-full shadow-[0_0_5px_1px_#fff] opacity-30"></div>
        </div>
        
        {/* Subtle Velvet Curtain Edges */}
        <div className="fixed inset-y-0 left-0 w-8 md:w-16 z-[-1] bg-gradient-to-r from-black/80 to-transparent pointer-events-none opacity-80 mix-blend-multiply" style={{backgroundImage: "url('https://images.unsplash.com/photo-1514302240736-b1fee59bea5f?q=80&w=600&auto=format&fit=crop')", backgroundSize: 'cover', backgroundBlendMode: 'multiply'}}></div>
        <div className="fixed inset-y-0 right-0 w-8 md:w-16 z-[-1] bg-gradient-to-l from-black/80 to-transparent pointer-events-none opacity-80 mix-blend-multiply" style={{backgroundImage: "url('https://images.unsplash.com/photo-1514302240736-b1fee59bea5f?q=80&w=600&auto=format&fit=crop')", backgroundSize: 'cover', backgroundBlendMode: 'multiply'}}></div>

        <Navbar />
        <main className="flex-1 mt-20 relative z-0">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
